/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.muhammadalqi.konversitemperatur;

/**
 *
 * @author Muhammad Alqi
 */
public class KonversiTemperaturInterface extends javax.swing.JFrame {

    /**
     * Creates new form KonversiTemperaturInterface
     */
    public KonversiTemperaturInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 255));
        setForeground(java.awt.Color.blue);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("APLIKASI PENGKONVERSI SUHU");

        jButton1.setText("Konversi");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Muhammad Alqi Fahrezi - 2A");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("=");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(">>>");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celcius", "Fahrenheit", "Kelvin", "Reamur" }));

        jButton2.setText("Hapus");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celcius", "Fahrenheit", "Kelvin", "Reamur" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addGap(32, 32, 32)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jButton1)
                                .addGap(42, 42, 42)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(166, 166, 166)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel3)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        //Menghapus nilai pada JTextField
        jTextField1.setText("");
        jTextField2.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
       //Mendapatkan elemen yang ada pada ComboBox agar dapat dibaca
       String field1 = (String)jComboBox1.getSelectedItem();
       String field2 = (String)jComboBox2.getSelectedItem();
       
       //1. Mengkonversi Celcius ke suhu lain
       if(field1.equals("Celcius") && field2.equals("Fahrenheit"))
       {
           double celcius = Double.parseDouble(jTextField1.getText());
           
           double fahrenheit = (double)(celcius * 1.8 + 32);
           
           jTextField2.setText(String.valueOf(fahrenheit));
       }
       else if(field1.equals("Celcius") && field2.equals("Kelvin"))
       {
           double celcius = Double.parseDouble(jTextField1.getText());
           
           double kelvin = (double)(celcius + 273.15 );
           
           jTextField2.setText(String.valueOf(kelvin));
       }
       else if(field1.equals("Celcius") && field2.equals("Reamur")){
           double celcius = Double.parseDouble(jTextField1.getText());
           
           double reamur = (double)(celcius * 0.8);
           
           jTextField2.setText(String.valueOf(reamur));
       }
       else if(field1.equals("Celcius") && field2.equals("Celcius"))
       {
           double celcius = Double.parseDouble(jTextField1.getText());
         
           jTextField2.setText(String.valueOf(celcius));
       }
       
       //2. Mengkonversi Fahrenheit ke suhu lain.
       if(field1.equals("Fahrenheit") && field2.equals("Celcius"))
       {
           double fahrenheit = Double.parseDouble(jTextField1.getText());
           
           double celcius = (double)((fahrenheit - 32) / 1.8);
           
           jTextField2.setText(String.valueOf(celcius));
       }
       else if(field1.equals("Fahrenheit") && field2.equals("Kelvin"))
       {
           double fahrenheit = Double.parseDouble(jTextField1.getText());
           
           double kelvin = (double)((fahrenheit + 459.67) / 1.8);
           
           jTextField2.setText(String.valueOf(kelvin));
       }
       else if(field1.equals("Fahrenheit") && field2.equals("Reamur")){
           double fahrenheit = Double.parseDouble(jTextField1.getText());
           
           double reamur = (double)((fahrenheit - 32) / 2.25);
           
           jTextField2.setText(String.valueOf(reamur));
       }
       else if(field1.equals("Fahrenheit") && field2.equals("Fahrenheit"))
       {
           double fahrenheit = Double.parseDouble(jTextField1.getText());
         
           jTextField2.setText(String.valueOf(fahrenheit));
       }
       
       //3. Mengkonversi Kelvin ke suhu lain
       if(field1.equals("Kelvin") && field2.equals("Celcius"))
       {
           double kelvin = Double.parseDouble(jTextField1.getText());
           
           double celcius = (double)(kelvin - 273.15);
           
           jTextField2.setText(String.valueOf(celcius));
       }
       else if(field1.equals("Kelvin") && field2.equals("Fahrenheit"))
       {
           double kelvin = Double.parseDouble(jTextField1.getText());
           
           double fahrenheit = (double)(kelvin * 1.8 - 459.67);
           
           jTextField2.setText(String.valueOf(fahrenheit));
       }
       else if(field1.equals("Kelvin") && field2.equals("Reamur")){
           double kelvin = Double.parseDouble(jTextField1.getText());
           
           double reamur = (double)((kelvin - 273.15) * 0.8);
           
           jTextField2.setText(String.valueOf(reamur));
       }
       else if(field1.equals("Kelvin") && field2.equals("Kelvin"))
       {
           double kelvin = Double.parseDouble(jTextField1.getText());
         
           jTextField2.setText(String.valueOf(kelvin));
       }
       
       //4. Mengkonversi Reamur ke suhu lain
         if(field1.equals("Reamur") && field2.equals("Celcius"))
       {
           double reamur = Double.parseDouble(jTextField1.getText());
           
           double celcius = (double)(reamur / 0.8);
           
           jTextField2.setText(String.valueOf(celcius));
       }
       else if(field1.equals("Reamur") && field2.equals("Fahrenheit"))
       {
           double reamur = Double.parseDouble(jTextField1.getText());
           
           double fahrenheit = (double)((reamur * 9/4) + 32);
           
           jTextField2.setText(String.valueOf(fahrenheit));
       }
       else if(field1.equals("Reamur") && field2.equals("Kelvin")){
           double reamur = Double.parseDouble(jTextField1.getText());
           
           double kelvin = (double)(reamur / 0.8 + 273.15);
           
           jTextField2.setText(String.valueOf(kelvin));
       }
       else if(field1.equals("Reamur") && field2.equals("Reamur"))
       {
           double reamur = Double.parseDouble(jTextField1.getText());
         
           jTextField2.setText(String.valueOf(reamur));
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KonversiTemperaturInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KonversiTemperaturInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KonversiTemperaturInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KonversiTemperaturInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KonversiTemperaturInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
